[PHP]
; Performances
memory_limit = 256M
max_execution_time = 30
realpath_cache_size= 4096K
realpath_cache_ttl = 600

; Uploads
upload_max_filesize = 20M
post_max_size = 20M

; Timezone
date.timezone = UTC

; Erreurs — désactivé en prod, géré par Monolog
display_errors = Off
log_errors = On

; amqp
extension=amqp.so
