doctrine_migrations:
    migrations_paths:
        'App\Shared\Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Migrations'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
