doctrine:
    dbal:
        driver: pdo_pgsql
        url: "%env(resolve:DATABASE_URL)%"
        types:
            user_id: App\User\Infrastructure\Persistence\Doctrine\Type\UserIdType
            email: App\Shared\Infrastructure\Persistence\Doctrine\Type\EmailType
            user_name: App\User\Infrastructure\Persistence\Doctrine\Type\UserNameType
            hashed_password: App\User\Infrastructure\Persistence\Doctrine\Type\HashedPasswordType
            user_status: App\User\Infrastructure\Persistence\Doctrine\Type\UserStatusType
            user_roles: App\User\Infrastructure\Persistence\Doctrine\Type\UserRolesType
            refresh_token_id: App\User\Infrastructure\Persistence\Doctrine\Type\RefreshTokenIdType
            document_id: App\Document\Infrastructure\Persistence\Doctrine\Type\DocumentIdType
            owner_id: App\Document\Infrastructure\Persistence\Doctrine\Type\OwnerIdType
            bucket_name: App\Document\Infrastructure\Persistence\Doctrine\Type\BucketNameType
            object_path: App\Document\Infrastructure\Persistence\Doctrine\Type\ObjectPathType
            document_mime_type: App\Document\Infrastructure\Persistence\Doctrine\Type\MimeTypeType
            document_status: App\Document\Infrastructure\Persistence\Doctrine\Type\DocumentStatusType
            multipart_upload_status: App\Document\Infrastructure\Persistence\Doctrine\Type\MultipartUploadStatusType
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            User:
                type: xml
                dir: "%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: App\User\Domain\Entity
                is_bundle: false
            refreshToken:
                type: xml
                dir: "%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: App\User\Domain\Entity
                is_bundle: false
            Document:
                type: xml
                dir: "%kernel.project_dir%/src/Document/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: App\Document\Domain\Entity
                is_bundle: false
when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
