doctrine_migrations:
    migrations_paths:
        'App\Shared\Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Migrations'
    enable_profiler: false
