framework:
    messenger:
        default_bus: command.bus
        failure_transport: async.dead_letter
        buses:
            command.bus:
                middleware:
                    - App\Shared\Infrastructure\Monitoring\Metrics\BusMetricsMiddleware
                    - App\Shared\Infrastructure\Monitoring\Tracing\TracerMiddleware
                    - App\Shared\Infrastructure\Messaging\AuthorizeMessageMiddleware
                    - App\Shared\Infrastructure\Messaging\FeatureFlagMessageMiddleware
                    - App\Shared\Infrastructure\Messaging\AuditMessageMiddleware
                    - doctrine_transaction
            query.bus:
                middleware:
                    - App\Shared\Infrastructure\Monitoring\Metrics\BusMetricsMiddleware
                    - App\Shared\Infrastructure\Monitoring\Tracing\TracerMiddleware
                    - App\Shared\Infrastructure\Messaging\AuthorizeMessageMiddleware
                    - App\Shared\Infrastructure\Messaging\FeatureFlagMessageMiddleware
            audit.bus:
                middleware:
                    - App\Shared\Infrastructure\Monitoring\Metrics\BusMetricsMiddleware
                    - App\Shared\Infrastructure\Monitoring\Tracing\TracerMiddleware
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Shared\Infrastructure\Monitoring\Metrics\BusMetricsMiddleware
                    - App\Shared\Infrastructure\Monitoring\Tracing\TracerMiddleware

        transports:
            sync: 'sync://'

            async:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: events
                        type: topic
                    queues:
                        events.user:
                            binding_keys: ['user.#']
                        events.document:
                            binding_keys: ['document.#']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            async.dead_letter:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: dead_letter
                        type: direct
                    queues:
                        dead_letter: ~
                retry_strategy:
                    max_retries: 0

        routing:
            'App\Shared\Domain\Bus\Command\Command': sync
            'App\Document\Application\Command\UploadDocument\RecordDocumentUploadFailureCommand': sync
            'App\Shared\Domain\Bus\Query\Query': sync
            'App\Shared\Domain\Bus\Event\DomainEvent': async
            'App\Shared\Infrastructure\Messaging\RabbitMQ\DeadLetterMessage': async.dead_letter
