<?php

declare(strict_types=1);

namespace App\Shared\Infrastructure\Console\Generator;

use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

final class BoundedContextRemover
{
    use GeneratorTrait;

    private const PROTECTED_CONTEXTS = ['Shared', 'User', 'Document'];

    public function __construct(
        private readonly string $projectDir,
        private readonly Filesystem $filesystem,
        private readonly CrudRemover $crudRemover,
    ) {
    }

    public function remove(string $context, SymfonyStyle $io): bool
    {
        if (\in_array($context, self::PROTECTED_CONTEXTS, true)) {
            $io->error(sprintf('Bounded Context "%s" is protected and cannot be removed.', $context));

            return false;
        }

        $srcDir = $this->projectDir.'/src/'.$context;

        if (!$this->filesystem->exists($srcDir)) {
            $io->error(sprintf('Bounded Context "%s" does not exist.', $context));

            return false;
        }

        $entities = $this->discoverEntities($srcDir);

        if ([] !== $entities) {
            $io->section('Entities');
            $io->writeln(sprintf('  Removing %d entit%s…', \count($entities), \count($entities) > 1 ? 'ies' : 'y'));

            foreach ($entities as $entity) {
                if (!$this->crudRemover->remove($context, $entity, $io)) {
                    return false;
                }
            }
        }

        $io->section('Bounded Context');
        $this->filesystem->remove($srcDir);
        $io->writeln(sprintf('  <info>removed</info> src/%s/', $context));

        $io->section('Tests');
        foreach (['Unit', 'Integration', 'Http'] as $suite) {
            $testDir = $this->projectDir.'/tests/'.$suite.'/'.$context;

            if (!$this->filesystem->exists($testDir)) {
                continue;
            }

            $this->filesystem->remove($testDir);
            $io->writeln(sprintf('  <info>removed</info> tests/%s/%s/', $suite, $context));
        }

        $io->section('Configuration');
        $this->unregisterRoutes($context, $io);
        $this->unregisterDoctrineMapping($context, $io);

        return true;
    }

    /**
     * @return list<string>
     */
    private function discoverEntities(string $srcDir): array
    {
        $entityDir = $srcDir.'/Domain/Entity';

        if (!$this->filesystem->exists($entityDir)) {
            return [];
        }

        $entities = [];

        $files = glob($entityDir.'/*.php');

        if (false === $files) {
            return [];
        }

        foreach ($files as $file) {
            $entities[] = basename($file, '.php');
        }

        sort($entities);

        return $entities;
    }

    private function unregisterRoutes(string $context, SymfonyStyle $io): void
    {
        $routesPath = $this->projectDir.'/config/routes.yaml';
        $content = file_get_contents($routesPath);

        if (false === $content) {
            $io->error('Could not read config/routes.yaml.');

            return;
        }

        $resource = '../src/'.$context.'/Infrastructure/Http/Controller/';
        $pattern = '/\n# Generated by make:bounded-context '.preg_quote($context, '/').'\napi_[^:\n]+:\n    resource: '.preg_quote($resource, '/').'\n    type: attribute\n    prefix: \/api\/[^\n]+(\n|$)/';
        $updated = preg_replace($pattern, '', $content, 1);

        if (null === $updated || $updated === $content) {
            $io->writeln(sprintf('  <comment>skipped</comment> Route for %s (not registered)', $context));

            return;
        }

        file_put_contents($routesPath, $updated);
        $io->writeln(sprintf('  <info>updated</info> config/routes.yaml (removed route for %s)', $context));
    }

    private function unregisterDoctrineMapping(string $context, SymfonyStyle $io): void
    {
        $path = $this->projectDir.'/config/packages/doctrine.yaml';
        $content = file_get_contents($path);

        if (false === $content) {
            $io->error('Could not read config/packages/doctrine.yaml.');

            return;
        }

        $pattern = '/            '.preg_quote($context, '/').':\n                type: xml\n                dir: "%kernel\.project_dir%\/src\/'.preg_quote($context, '/').'\/Infrastructure\/Persistence\/Doctrine\/Mapping"\n                prefix: App\\\\'.preg_quote($context, '/').'\\\\Domain\\\\Entity\n                is_bundle: false\n/';
        $updated = preg_replace($pattern, '', $content, 1);

        if (null === $updated || $updated === $content) {
            $io->writeln(sprintf('  <comment>skipped</comment> Doctrine mapping %s (not registered)', $context));

            return;
        }

        file_put_contents($path, $updated);
        $io->writeln(sprintf('  <info>updated</info> config/packages/doctrine.yaml (removed mapping %s)', $context));
    }
}
