<?php

declare(strict_types=1);

namespace App\Shared\Infrastructure\Console\Generator;

use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

final class BoundedContextGenerator
{
    use GeneratorTrait;

    private const DIRECTORIES = [
        'Domain/Entity',
        'Domain/ValueObject',
        'Domain/Repository',
        'Domain/Event',
        'Domain/Exception',
        'Application/Command',
        'Application/Query',
        'Infrastructure/Http/Controller',
        'Infrastructure/Http/Request',
        'Infrastructure/Persistence/Doctrine/Mapping',
        'Infrastructure/Persistence/Doctrine/Repository',
        'Infrastructure/Persistence/Doctrine/Type',
        'Infrastructure/Fixture',
        'Infrastructure/Messaging',
    ];

    public function __construct(
        private readonly string $projectDir,
        private readonly Filesystem $filesystem,
    ) {
    }

    public function generate(string $name, string $version, SymfonyStyle $io): void
    {
        $srcDir = $this->projectDir.'/src/'.$name;

        $io->section('Structure');

        foreach (self::DIRECTORIES as $directory) {
            $path = $srcDir.'/'.$directory;
            $this->filesystem->mkdir($path);
            $this->filesystem->dumpFile($path.'/.gitkeep', '');
            $io->writeln(sprintf('  <info>created</info> %s/', $directory));
        }

        $io->section('Configuration');

        $this->registerRoutes($name, $version, $io);
        $this->registerDoctrineMapping($name, $io);
    }

    private function registerRoutes(string $name, string $version, SymfonyStyle $io): void
    {
        $routesPath = $this->projectDir.'/config/routes.yaml';
        $content = file_get_contents($routesPath);

        if (false === $content) {
            $io->error('Could not read config/routes.yaml.');

            return;
        }

        $routeKey = 'api_'.$version.'_'.$this->toSnakeCase($name);

        if (str_contains($content, $routeKey.':')) {
            $io->writeln(sprintf('  <comment>skipped</comment> Route %s (already registered)', $routeKey));

            return;
        }

        $entry = <<<YAML

# Generated by make:bounded-context {$name}
{$routeKey}:
    resource: ../src/{$name}/Infrastructure/Http/Controller/
    type: attribute
    prefix: /api/{$version}
YAML;

        file_put_contents($routesPath, $content.$entry);
        $io->writeln(sprintf('  <info>updated</info> config/routes.yaml (route %s)', $routeKey));
    }

    private function registerDoctrineMapping(string $name, SymfonyStyle $io): void
    {
        $path = $this->projectDir.'/config/packages/doctrine.yaml';
        $content = file_get_contents($path);

        if (false === $content) {
            $io->error('Could not read config/packages/doctrine.yaml.');

            return;
        }

        $entry = <<<YAML
            {$name}:
                type: xml
                dir: "%kernel.project_dir%/src/{$name}/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: App\\{$name}\\Domain\\Entity
                is_bundle: false

YAML;

        if (str_contains($content, "            {$name}:\n                type: xml")) {
            $io->writeln(sprintf('  <comment>skipped</comment> Doctrine mapping %s (already registered)', $name));

            return;
        }

        $updated = preg_replace(
            '/(        mappings:\n(?:            .+\n)+)/',
            '$1'.$entry,
            $content,
            1,
        );

        if (null === $updated || $updated === $content) {
            $io->error('Could not register Doctrine mapping automatically.');

            return;
        }

        file_put_contents($path, $updated);
        $io->writeln(sprintf('  <info>updated</info> config/packages/doctrine.yaml (mapping %s)', $name));
    }
}
