services:
    App\Shared\Infrastructure\Http\Serializer\ValueObjectNormalizer:
        tags: [serializer.normalizer]

    App\Shared\Infrastructure\Http\Serializer\ResponseNormalizer:
        tags: [serializer.normalizer]

    App\Shared\Infrastructure\Http\Response\ApiResponse:
        arguments:
            $serializer: '@serializer'

    App\Shared\Infrastructure\Bus\Command\MessengerCommandBus:
        arguments:
            $commandBus: '@command.bus'

    App\Shared\Infrastructure\Bus\Query\MessengerQueryBus:
        arguments:
            $queryBus: '@query.bus'

    App\Shared\Infrastructure\Bus\Event\MessengerEventBus:
        arguments:
            $eventBus: '@event.bus'

    App\Shared\Domain\Logging\LoggerInterface:
        alias: App\Shared\Infrastructure\Logging\MonologLogger

    # Define the http listner
    App\Shared\Infrastructure\Http\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

    # Define the http headers
    App\Shared\Infrastructure\Http\Listener\ApiHeadersListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository
