services:
    App\Shared\Infrastructure\Bus\Command\MessengerCommandBus:
        arguments:
            $commandBus: '@command.bus'

    App\Shared\Infrastructure\Bus\Query\MessengerQueryBus:
        arguments:
            $queryBus: '@query.bus'

    App\Shared\Infrastructure\Bus\Event\MessengerEventBus:
        arguments:
            $eventBus: '@event.bus'

    App\Shared\Domain\Logging\LoggerInterface:
        alias: App\Shared\Infrastructure\Logging\MonologLogger

    # Define the http listner
    App\Shared\Infrastructure\Http\Listener\ExceptionListener:
            tags:
                - { name: kernel.event_listener, event: kernel.exception, priority: 100 }
